//! Auto-generated SoccerGet* dropdown labels (index -> label).
//! Source: AIGamePyLibrary.data.DROPDOWN_OPTIONS
//! Regenerate: python scripts/gen_graph_dropdowns.py

pub const SOCCER_GET_BOOL: &[&str] = &[
    "Team Has Ball",
    "Opponent Has Ball",
    "Is Ball Loose",
    "Team Player 1 Has Ball",
    "Team Player 2 Has Ball",
    "Team Player 3 Has Ball",
    "Team Player 4 Has Ball",
    "Opponent Player 1 Has Ball",
    "Opponent Player 2 Has Ball",
    "Opponent Player 3 Has Ball",
    "Opponent Player 4 Has Ball",
    "Is Ball Nearby Team Player 1",
    "Is Ball Nearby Team Player 2",
    "Is Ball Nearby Team Player 3",
    "Is Ball Nearby Team Player 4",
    "Is Ball Nearby Opponent Player 1",
    "Is Ball Nearby Opponent Player 2",
    "Is Ball Nearby Opponent Player 3",
    "Is Ball Nearby Opponent Player 4",
    "Is Team Player 1 Closest Teammate to Ball",
    "Is Team Player 2 Closest Teammate to Ball",
    "Is Team Player 3 Closest Teammate to Ball",
    "Is Team Player 4 Closest Teammate to Ball",
    "Is Opponent Player 1 Closest Opponent to Ball",
    "Is Opponent Player 2 Closest Opponent to Ball",
    "Is Opponent Player 3 Closest Opponent to Ball",
    "Is Opponent Player 4 Closest Opponent to Ball",
    "Is Team Player 1 Open",
    "Is Team Player 2 Open",
    "Is Team Player 3 Open",
    "Is Team Player 4 Open",
    "Is Opponent Player 1 Open",
    "Is Opponent Player 2 Open",
    "Is Opponent Player 3 Open",
    "Is Opponent Player 4 Open",
    "Is Kickoff",
    "Is Team Kicking off",
    "Is Opponent Kicking off",
    "Team Is Winning",
    "Opponent Is Winning",
    "Team Scored Last Point",
    "Opponent Scored Last Point",
    "Ball On Team Side",
    "Ball On Opponent Side",
    "Is Ball Headed Towards Team Goal",
    "Is Ball Headed Towards Opponent Goal",
    "Is Home Team",
    "Is Away Team",
    "Is Active Graph",
];

pub const SOCCER_GET_FLOAT: &[&str] = &[
    "Team Score",
    "Opponent Score",
    "Team Shots",
    "Opponent Shots",
    "Team Possession %",
    "Opponent Possession %",
    "Team Attacking %",
    "Opponent Attacking %",
    "Ball Speed",
    "Player Interact Radius",
    "Player With Ball Shot Charge %",
    "Ball Carrier Stamina",
    "Ball Carrier Shot Charge",
    "Teammate 1 Shot Charge",
    "Teammate 2 Shot Charge",
    "Teammate 3 Shot Charge",
    "Teammate 4 Shot Charge",
    "Field Width",
    "Field Depth",
    "Kickoff Circle Radius",
    "Goal Width",
    "Goal Height",
    "Team Player 1 Stamina",
    "Team Player 2 Stamina",
    "Team Player 3 Stamina",
    "Team Player 4 Stamina",
    "Distance from Team Player 1 to nearest Opponent",
    "Distance from Team Player 2 to nearest Opponent",
    "Distance from Team Player 3 to nearest Opponent",
    "Distance from Team Player 4 to nearest Opponent",
    "Opponent Player 1 Stamina",
    "Opponent Player 2 Stamina",
    "Opponent Player 3 Stamina",
    "Opponent Player 4 Stamina",
    "Opponent Nearest Teammate Player 1 Stamina",
    "Opponent Nearest Teammate Player 2 Stamina",
    "Opponent Nearest Teammate Player 3 Stamina",
    "Opponent Nearest Teammate Player 4 Stamina",
    "Stamina of last defending opponent",
    "Current Simulation Time",
    "Max Simulation Time",
    "Simulation Time Remaining",
    "Delta Time",
    "Fixed Delta Time",
    "Pi",
];

pub const SOCCER_GET_TRANSFORM: &[&str] = &[
    "Ball",
    "Team Player 1",
    "Team Player 2",
    "Team Player 3",
    "Team Player 4",
    "Opponent Player 1",
    "Opponent Player 2",
    "Opponent Player 3",
    "Opponent Player 4",
    "Teammate Nearest Team Player 1",
    "Teammate Nearest Team Player 2",
    "Teammate Nearest Team Player 3",
    "Teammate Nearest Team Player 4",
    "Opponent Nearest Team Player 1",
    "Opponent Nearest Team Player 2",
    "Opponent Nearest Team Player 3",
    "Opponent Nearest Team Player 4",
    "Team Goal Center",
    "Team Goal Left Post",
    "Team Goal Right Post",
    "Opponent Goal Center",
    "Opponent Goal Left Post",
    "Opponent Goal Right Post",
    "Opponent Nearest Team Goal",
    "Opponent Nearest Opponent Goal",
    "Teammate Nearest Team Goal",
    "Teammate Nearest Opponent Goal",
];

pub const SOCCER_GET_VECTOR3: &[&str] = &[
    "Ball Velocity",
    "Clear direction from team carrier",
    "Backwards clear direction from team carrier",
    "Clear direction from team carrier (avoid goal lines)",
    "Clear direction from team carrier (avoid sidelines)",
    "Clear direction from team carrier (avoid all walls)",
    "Upper Corner Home Side",
    "Lower Corner Home Side",
    "Upper Midfield",
    "Lower Midfield",
    "Upper Corner Away Side",
    "Lower Corner Away Side",
    "Upper Corner Opposing Side",
    "Lower Corner Opposing Side",
    "Upper Corner Team Side",
    "Lower Corner Team Side",
    "Center Field",
    "Get nearest open teammate",
    "Get furthest open teammate",
    "Get most open teammate",
    "Get nearest open opponent",
    "Get furthest open opponent",
    "Get most open opponent",
    "Direction of clear teammate from Teammate 1",
    "Direction of clear teammate from Teammate 2",
    "Direction of clear teammate from Teammate 3",
    "Direction of clear teammate from Teammate 4",
    "Direction of clear teammate from Opponent 1",
    "Direction of clear teammate from Opponent 2",
    "Direction of clear teammate from Opponent 3",
    "Direction of clear teammate from Opponent 4",
    "Direction of ball from Teammate 1",
    "Direction of ball from Teammate 2",
    "Direction of ball from Teammate 3",
    "Direction of ball from Teammate 4",
    "Direction of ball from Opponent 1",
    "Direction of ball from Opponent 2",
    "Direction of ball from Opponent 3",
    "Direction of ball from Opponent 4",
    "Direction of team goal from Teammate 1",
    "Direction of team goal from Teammate 2",
    "Direction of team goal from Teammate 3",
    "Direction of team goal from Teammate 4",
    "Direction of opponent goal from Teammate 1",
    "Direction of opponent goal from Teammate 2",
    "Direction of opponent goal from Teammate 3",
    "Direction of opponent goal from Teammate 4",
    "Clear direction from Teammate 1",
    "Clear direction from Teammate 2",
    "Clear direction from Teammate 3",
    "Clear direction from Teammate 4",
    "Direction of teammate from Team Player 1",
    "Direction of teammate from Team Player 2",
    "Direction of teammate from Team Player 3",
    "Direction of teammate from Team Player 4",
];

pub fn resolve<'a>(node_id: &str, modifier: &'a str) -> &'a str {
    let opts: &[&str] = match node_id {
        "SoccerGetBool" => SOCCER_GET_BOOL,
        "SoccerGetFloat" => SOCCER_GET_FLOAT,
        "SoccerGetTransform" => SOCCER_GET_TRANSFORM,
        "SoccerGetVector3" => SOCCER_GET_VECTOR3,
        _ => return modifier,
    };
    if let Ok(i) = modifier.parse::<usize>() {
        if let Some(label) = opts.get(i) {
            return label;
        }
    }
    modifier
}
